#Faça um programa que leia algo pelo teclado e mostre na tela o
# seu tipo primitivo e mostre todas as informações disponiveis
n = input('Digite algo: ')
print('is numeric?')
print(n.isnumeric())
print('is alpha')
print(n.isalpha())
print('is alpha numeric?')
print(n.isalnum())
print('is upper?')
print(n.isupper())
print('is digit?')
print(n.isdigit())
print('is lower?')
print(n.islower())
print('is printable')
print(n.isprintable())
print('is space')
print(n.isspace())
print('is identifier')
print(n.isidentifier())
print('is title?(capitalizada)')
print(n.istitle())
print('is identifier')
print(n.isidentifier())