n = float(input('Digite um valor: '))
print(n)
n = bool(input('Digite um valor: '))
print(n)
n = float(input('Digite um valor: '))
print(n)
n = str(input('Digite um valor: '))
print(n)
n = input('Digite algo: ')
print('is numeric?')
print(n.isnumeric())
print('is alpha')
print(n.isalpha())
print('is alpha numeric?')
print(n.isalnum())
print('is upper?')
print(n.isupper())
print('is digit?')
print(n.isdigit())
print('is lower?')
print(n.islower())
print('is printable')
print(n.isprintable())
print('is space')
print(n.isspace())
print('is identifier')
print(n.isidentifier())